"use client";

import { createContext, useContext, useState, useEffect, ReactNode, useCallback, useMemo } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traductions
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    "navbar.overview": "Overview",
    "navbar.coach": "Coach",
    "navbar.backToMatches": "Retour aux matchs",
    "navbar.profile": "Profil",
    "navbar.pro": "Pro",
    "navbar.settings": "Paramètres",
    "navbar.manageSubscription": "Gérer mon abonnement",
    "navbar.upgradeToPro": "Passer à Pro",
    "navbar.logout": "Se déconnecter",
    "navbar.userTierFree": "Tier Gratuit",
    "navbar.userTierPro": "Tier Pro",
    
    // Settings
    "settings.title": "Paramètres",
    "settings.subtitle": "Gère ton compte et tes préférences TheCall.",
    "settings.language": "Langue",
    "settings.languageDesc": "Choisis la langue de l'interface",
    "settings.saving": "Sauvegarde...",
    "settings.saved": "Enregistré !",
    "settings.save": "Sauvegarder",
    "settings.logout": "Déconnexion",
    "settings.saveError": "Erreur lors de la sauvegarde. Réessaye.",
    "settings.futureSettings": "D'autres paramètres seront disponibles prochainement",
    "settings.tabs.account": "Compte",
    "settings.tabs.subscription": "Abonnement",
    "settings.tabs.preferences": "Préférences",
    "settings.tabs.security": "Sécurité",
    "settings.tabs.notifications": "Notifications",
    "settings.personalInfo": "Informations Personnelles",
    "settings.personalInfoDesc": "Ces informations sont synchronisées via Riot Games et ne peuvent pas être modifiées manuellement.",
    "settings.name": "Prénom / Pseudo",
    "settings.email": "Email",
    "settings.riotLink": "Lien Riot Games",
    "settings.riotConnected": "Compte Riot Connecté",
    "settings.plan.title": "Ton Plan Actuel",
    "settings.plan.free": "Plan Gratuit",
    "settings.plan.pro": "TheCall Pro",
    "settings.plan.active": "Membre Actif",
    "settings.plan.upgrade": "Passer à Pro",
    "settings.plan.freeDesc": "Limite de {count} analyses par mois. Passe à Pro pour ne plus rien rater.",
    "settings.plan.proDesc": "Tu bénéficies de toutes les analyses premium illimitées.",
    "settings.billing.title": "Détails de Facturation",
    "settings.billing.status": "Statut",
    "settings.billing.renewal": "Renouvellement",
    "settings.billing.founder": "Membre Fondateur",
    "settings.billing.founderThanks": "Merci d'avoir soutenu TheCall au lancement ! 💜",
    "settings.billing.manage": "Gérer mon abonnement via Stripe",
    "settings.billing.adminManaged": "Géré par un Administrateur",
    "settings.billing.cancelNotice": "Sera annulé à cette date",
    "settings.usage.title": "Utilisation",
    "settings.usage.analyses": "Analyses ce mois",
    "settings.look.title": "Interface & Look",
    "settings.look.dynamicTheme": "Thème Dynamique",
    "settings.look.dynamicThemeDesc": "L'interface adapte ses teintes (Victoire, Défaite ou Neutre) en fonction du résultat de tes matchs.",
    "settings.look.animations": "Animations Avancées",
    "settings.look.animationsDesc": "Active les transitions fluides, les effets de particules et les micro-interactions.",
    "settings.privacy.title": "Confidentialité",
    "settings.privacy.public": "Profil Public",
    "settings.privacy.publicDesc": "Permet aux autres joueurs de voir tes statistiques et rapports.",
    "settings.security.password": "Mot de Passe",
    "settings.security.unavailable": "Changement de mot de passe (Indisponible pour le moment)",
    "settings.notifications.channels": "Canaux",
    "settings.notifications.push": "Notifications Push",
    "settings.notifications.pushDesc": "Alerte quand un nouveau rapport est prêt.",
    "settings.notifications.newsletter": "Newsletter & Conseils",
    "settings.notifications.newsletterDesc": "Reçois les meilleures astuces hebdomadaires par email.",
    
    // Subscription
    "subscription.title": "Gestion de l'abonnement",
    "subscription.subtitle": "Gère ton abonnement Pro",
    "subscription.planPro": "Plan Pro",
    "subscription.planFree": "Plan Gratuit",
    "subscription.proDesc": "Accès complet à toutes les fonctionnalités",
    "subscription.freeDesc": "Accès limité aux fonctionnalités de base",
    "subscription.active": "ACTIF",
    "subscription.renewalDate": "Renouvellement automatique le",
    "subscription.cancelling": "Ton abonnement sera annulé à la fin de la période de facturation",
    "subscription.actions": "Actions",
    "subscription.cancel": "Annuler l'abonnement",
    "subscription.reactivate": "Réactiver l'abonnement",
    "subscription.downgrade": "Passer en gratuit immédiatement",
    "subscription.upgradeTitle": "Passe à Pro",
    "subscription.upgradeDesc": "Débloque toutes les fonctionnalités premium",
    "subscription.viewOffers": "Voir les offres",
    "subscription.paymentInfo": "Informations de paiement",
    "subscription.paymentInfoDesc": "La gestion des méthodes de paiement sera disponible prochainement",
    "subscription.cancelConfirmTitle": "Annuler l'abonnement ?",
    "subscription.cancelConfirmDesc": "Ton abonnement restera actif jusqu'à la fin de la période de facturation ({date}). Tu pourras toujours réactiver avant cette date.",
    "subscription.downgradeConfirmTitle": "Passer en gratuit ?",
    "subscription.downgradeConfirmDesc": "Tu perdras immédiatement l'accès aux fonctionnalités Pro. Cette action est irréversible jusqu'à ce que tu repasses à Pro.",
    "subscription.processing": "Traitement...",
    "subscription.confirm": "Confirmer",
    "subscription.cancelAction": "Annuler",
    "subscription.loading": "Chargement...",
    
    // Landing Page
    "landing.beta": "Beta privée",
    "landing.focus": "Focus macro",
    "landing.postGame": "Post-game coaching",
    "landing.tagline": "The Call • Coaching League of Legends",
    "landing.title": "Tu es stuck et tu ne comprends pas pourquoi ?",
    "landing.titleHighlight": "TheCall",
    "landing.titleEnd": "te montre où la game bascule.",
    "landing.subtitle": "Ton analyste macro haute précision.",
    "landing.description": "Arrête de spammer les games dans le vide. Détecte le moment exact où tu perds le contrôle, la vraie cause racine (macro, tempo, vision), et applique un plan de jeu clair pour carry la prochaine.",
    "landing.analyzeButton": "Analyser ma dernière game",
    "landing.riotConnect": "Connexion Riot (bientôt)",
    "landing.riotConnectTitle": "Connexion Riot via RSO — en cours de validation",
    "landing.fastReport": "Analyse flash < 5s",
    "landing.roleAdapted": "Insights calibrés pour ton rôle (Top → Supp)",
    "landing.taglineShort": "Moment clé • Cause racine • Plan d'action",
    "landing.targetAudience": "Pour les joueurs Bronze → Gold qui veulent monter d'un palier. Pas de conseils génériques : des insights exploitables.",
    "landing.riotIdLabel": "Entrer mon Riot ID",
    "landing.riotIdPlaceholder": "BNJ#EUW",
    "landing.riotIdFormat": "Format : gameName#tag (ex : BNJ#EUW)",
    "landing.analyzeButtonForm": "Analyser",
    "landing.feature1Title": "Le moment clé",
    "landing.feature1Desc": "Tu vois le moment précis où la game bascule — et la cause (prio, vision, reset, fight forcé). Plus de \"j'ai mal joué\" vague : tu sais exactement quoi corriger.",
    "landing.feature1Proof": "Moment clé : 15:23 (Herald Flight)",
    "landing.feature2Title": "La cause racine",
    "landing.feature2Desc": "On t'explique pourquoi la game t'échappe. Gagner ta lane ne suffit pas : comprends le déséquilibre structurel (tempo, vision, rotations) qui t'empêche de concétriser.",
    "landing.feature2Proof": "Cause : tempo lâché à 12 min",
    "landing.feature3Title": "Ton plan next game",
    "landing.feature3Desc": "Une consigne simple et actionnable pour ta prochaine partie. Pas une analyse de plus : une instruction à appliquer immédiatement.",
    "landing.feature3Proof": "Plan : reset + vision 40s avant",
    "landing.exampleTitle": "Exemple de rapport",
    "landing.exampleKeyMoment": "Moment clé",
    "landing.exampleKeyMomentText": "15:23 — Contest Herald perdu (Vision déficiente).",
    "landing.exampleKeyMomentConsequence": "Conséquence : Perte tempo map, T1 Mid exposée. La game bascule 60/40 pour eux.",
    "landing.exampleRootCause": "Cause racine",
    "landing.exampleRootCauseText": "Gold lead +1.2k stérile : aucune conversion en map pressure.",
    "landing.exampleRootCauseDetail": "Tu domines ton vis-à-vis mais tu restes passif. Tes roams arrivent 15s trop tard pour impacter les side-lanes.",
    "landing.exampleAction": "Action suivante",
    "landing.exampleActionText": "14:40 — Reset + vision river bot.",
    "landing.exampleActionDetail": "Arrive 10s en avance pour setup avant Drake spawn. Tu reprends le tempo.",
    "landing.howItWorks1": "On récupère ta dernière partie (via Riot API).",
    "landing.howItWorks2": "On isole le moment clé + ton focus prioritaire.",
    "landing.howItWorks3": "Tu repars avec une action simple à appliquer next game.",
    "landing.coachingTitle": "Le standard TheCall",
    "landing.coachingSubtitle": "En 60 secondes : 1 moment clé, 1 focus, 1 action next game.",
    "landing.coachingExample": "Exemple de retours que tu peux recevoir",
    "landing.coachingExample1": "Gold ahead mais tempo lâché : on pointe le moment où tu perds la main et pourquoi.",
    "landing.coachingExample2": "Lead lane mais impact global faible : on te dit comment corriger (rotations + objectifs dès 12 min).",
    "landing.previewWinProb": "Probabilité de victoire • Exemple",
    "landing.previewWinProbValue": "72% victoire • Mid game",
    "landing.previewKeyMoment": "Moment clé :",
    "landing.previewHerald": "fight Herald perdu",
    "landing.previewMacro": "Macro",
    "landing.previewMacroScore": "Bon tempo",
    "landing.previewMacroValue": "Score : 78/100",
    "landing.previewLaning": "Laning",
    "landing.previewLaningScore": "Avantage",
    "landing.previewLaningValue": "Score : 84/100",
    "landing.previewDecisions": "Décisions",
    "landing.previewDecisionsScore": "À corriger",
    "landing.previewDecisionsValue": "Score : 62/100",
    
    // Matches
    "matches.title": "Mes matchs",
    "matches.subtitle": "Sélectionne un match pour voir les détails",
    "matches.noMatches": "Aucun match disponible",
    "matches.error": "Service perturbé",
    "matches.errorDesc": "La communication avec les services Riot est difficile.",
    "matches.errorSolution": "Pistes :",
    "matches.errorStep1": "Vérifie ta connexion internet",
    "matches.errorStep2": "Les serveurs Riot sont peut-être surchargés",
    "matches.errorStep3": "Réessaie dans quelques instants",
    "matches.loading": "Chargement des matchs...",
    "matches.selectMatch": "Sélectionne un match",
    
    // Common
    "common.back": "Retour",
    "common.loading": "Chargement...",
    "common.guest": "Invité",
    "settings.french": "Français",
    "settings.english": "Anglais",
    "subscription.upgradeConfirmTitle": "Passer à Pro ? (Mode Dev)",
    "subscription.upgradeConfirmDesc": "En mode développement, tu peux tester le passage en Pro. La page sera rechargée pour appliquer les changements.",
    
    // Loading
    "loading.messages.poro": "Caresses aux Poros...",
    "loading.messages.stats": "Calcul des statistiques...",
    "loading.messages.gameplay": "Analyse du gameplay...",
    "loading.messages.nexus": "Inspection du Nexus...",
    "loading.messages.runes": "Chargement des éclats de runes...",
    
    // Tips
    "tips.herald": "Conseil : Frappe l'œil dans le dos du Héraut pour lui infliger d'énormes dégâts brut.",
    "tips.wards": "Conseil : Garde ta balise gratuite pour détecter une invasion dès la première minute.",
    "tips.recall": "Conseil : Ne reste pas avec 1500 golds en poche. Reset pour transformer ton avantage en objets.",
    "tips.objective": "Conseil : Un kill sans objectif (tour, drake) n'est qu'une statistique, pas une victoire.",
    "tips.spacing": "Conseil : Le spacing est la clé. Garde la distance maximale pour punir sans être puni.",
    "tips.level2": "Conseil : Le premier camp (jungle) ou la 7ème mort (lane) donne le niveau 2. Anticipe !",
    "tips.vision": "Conseil : La Vision Score n'est pas que pour les supports. Pose des wards profondes.",
    "tips.tempo": "Conseil : Le tempo est une ressource. Si tu attends trop, l'opportunité disparaît.",
    
    // Match
    "match.notFound": "Match introuvable",
    "match.notFoundDesc": "Ce match n'existe pas dans ta liste.",
    "match.unavailable": "Match indisponible",
    "match.unavailableDesc": "Impossible de charger les détails de ce match.",
    "match.noOpponent": "Impossible d'identifier un vis-à-vis (role match).",
    "match.matchCenter": "The Call • Match Center",
    "match.matchOverview": "Match Overview",
    "match.matchOverviewDesc": "Timeline, duel, builds et audit IA — style client LoL.",
    "match.result": "Résultat",
    "match.yourRole": "Ton rôle",
    "match.yourChampion": "Ton champion",
    "match.timelineTitle": "Timeline",
    "match.timelineSubtitle": "Événements clés de la partie",
    "match.duelTitle": "Duel",
    "match.duelSubtitle": "Toi vs ton vis-à-vis",
    "match.buildsTitle": "Builds",
    "match.buildsSubtitle": "Items & runes utilisés dans la partie",
    "match.teamsTitle": "Équipes",
    "match.teamsSubtitle": "Composition des équipes",
    "match.yourTeam": "Ton équipe",
    "match.enemyTeam": "Équipe adverse",
    "match.you": "Toi",
    "match.opponent": "Adversaire",
    
    // Builds
    "build.yourBuild": "Ton build",
    "build.opponentBuild": "Build de l'adversaire",
    "build.title": "Build dans la partie",
    "build.subtitle": "Items & runes utilisés dans la game",
    "build.items": "Items",
    "build.runes": "Runes",
    
    // Auth
    "auth.title": "Connexion via Riot",
    "auth.subtitle": "Auth Riot (placeholder)",
    "auth.description": "Cette page est prête pour brancher l'OAuth Riot (client_id, redirect_uri, scopes). On redirigera l'utilisateur vers l'URL d'autorisation, puis on traitera le code de retour pour échanger un token et récupérer le PUUID.",
    "auth.vars": "Prévois les vars: RIOT_CLIENT_ID, RIOT_CLIENT_SECRET, RIOT_REDIRECT_URI.",
    "auth.waiting": "En attendant l'OAuth, tu peux passer en mode \"déjà connecté\" via le lien ci-dessous.",
    "auth.continue": "Continuer (mock connecté)",
    "auth.back": "Retour à l'accueil",
    
    // Match List
    "matchList.loading": "Chargement...",
    "matchList.vs": "VS",
    "matchList.vsShort": "vs",
    "matchList.victory": "VICTOIRE",
    "matchList.defeat": "DÉFAITE",
    "matchList.victoryShort": "V",
    "matchList.defeatShort": "D",
    "matchList.queueRankedSolo": "Ranked Solo",
    "matchList.queueRankedFlex": "Ranked Flex",
    "matchList.queueAram": "ARAM",
    "matchList.queueNormalDraft": "Normal Draft",
    "matchList.queueClash": "Clash",
    "matchList.queueNormal": "Normal",
    "matchList.totalGames": "Games",
    "matchList.winrate": "WinRate",
    
    // Match Type Filter
    "matchType.all": "Toutes les parties",
    "matchType.draft": "Draft",
    "matchType.ranked": "Classées",
    
    // Cookies
    "cookies.title": "Nous utilisons des cookies",
    "cookies.description": "Nous utilisons des cookies pour améliorer ton expérience, gérer les sessions et analyser l'utilisation du site. En continuant, tu acceptes notre utilisation des cookies.",
    "cookies.acceptAll": "Tout accepter",
    "cookies.rejectAll": "Tout refuser",
    "cookies.customize": "Personnaliser",
    "cookies.settingsTitle": "Paramètres des cookies",
    "cookies.savePreferences": "Enregistrer les préférences",
    "cookies.learnMore": "En savoir plus",
    "cookies.necessaryTitle": "Cookies nécessaires",
    "cookies.necessaryDesc": "Ces cookies sont essentiels au fonctionnement du site. Ils ne peuvent pas être désactivés.",
    "cookies.functionalTitle": "Cookies fonctionnels",
    "cookies.functionalDesc": "Ces cookies permettent d'améliorer les fonctionnalités comme le rate limiting et la gestion des sessions pour une meilleure expérience.",
    "cookies.analyticsTitle": "Cookies analytiques",
    "cookies.analyticsDesc": "Ces cookies nous aident à comprendre comment tu utilises le site pour l'améliorer.",
    "cookies.alwaysActive": "Toujours actif",
    
    // Privacy
    "privacy.title": "Politique de confidentialité",
    "privacy.subtitle": "Protection de tes données et utilisation des cookies",
    "privacy.intro": "Chez TheCall, nous respectons ta vie privée et nous nous engageons à protéger tes données personnelles. Cette politique explique comment nous collectons, utilisons et protégeons tes informations.",
    "privacy.cookiesTitle": "Utilisation des cookies",
    "privacy.necessaryCookies": "Cookies nécessaires",
    "privacy.necessaryCookiesDesc": "Ces cookies sont essentiels au fonctionnement du site. Ils permettent de maintenir ta session, de sécuriser les requêtes et d'assurer le bon fonctionnement des fonctionnalités de base. Ils ne peuvent pas être désactivés.",
    "privacy.functionalCookies": "Cookies fonctionnels",
    "privacy.functionalCookiesDesc": "Ces cookies améliorent ton expérience en permettant le rate limiting personnalisé, la gestion des sessions et d'autres fonctionnalités qui nécessitent de te reconnaître entre les visites. Tu peux les accepter ou les refuser.",
    "privacy.analyticsCookies": "Cookies analytiques",
    "privacy.analyticsCookiesDesc": "Ces cookies nous aident à comprendre comment tu utilises le site (pages visitées, temps passé, etc.) pour améliorer nos services. Tu peux les accepter ou les refuser.",
    "privacy.dataTitle": "Données collectées",
    "privacy.dataDesc": "Nous collectons uniquement les données nécessaires au fonctionnement du service :",
    "privacy.dataList1": "Riot ID et données de match (via l'API Riot Games)",
    "privacy.dataList2": "Préférences de langue et paramètres de l'interface",
    "privacy.dataList3": "Données de session pour le rate limiting et la sécurité",
    "privacy.rightsTitle": "Tes droits (RGPD)",
    "privacy.rightsDesc": "Conformément au RGPD, tu as le droit de :",
    "privacy.rightsList1": "Accéder à tes données personnelles",
    "privacy.rightsList2": "Rectifier ou supprimer tes données",
    "privacy.rightsList3": "T'opposer au traitement de tes données",
    "privacy.rightsList4": "Retirer ton consentement à tout moment",
    "privacy.contactTitle": "Contact",
    "privacy.contactDesc": "Pour toute question sur cette politique ou pour exercer tes droits, contacte-nous via les canaux de support disponibles.",
    "footer.legal": "Mentions Légales",
    "footer.privacy": "Cookie & Privacy",
    "footer.crafted": "Crafted with ❤️ by TheCall Team.",
    
    // Match Page - Error messages
    "match.puuidMissing": "PUUID manquant",
    "match.puuidMissingDesc": "Ajoute",
    "match.puuidMissingIn": "dans",
    
    // Coaching
    "coaching.title": "Coaching TheCall",
    "coaching.subtitle": "Analyse post-match avec insights personnalisés",
    "coaching.progressionObjectives": "Objectifs de progression",
    "coaching.moreObjectives": "+{count} autres objectifs disponibles avec Pro",
    "coaching.strengths": "Points forts",
    "coaching.weaknesses": "Points à améliorer",
    "coaching.moreStrengths": "+{count} autres points forts avec Pro",
    "coaching.moreWeaknesses": "+{count} autres points à améliorer avec Pro",
    "coaching.errorsToAvoid": "Erreurs à éviter :",
    "coaching.games": "games",
    "coaching.quotaExhausted": "Quota coaching épuisé",
    "coaching.quotaExhaustedDesc": "Upgrade Pro pour coaching illimité + profil complet",
    "coaching.impact": "Impact:",
    "coaching.aiLoading": "L'IA analyse ta partie...",
    
    // Profile
    "profile.title": "The Call • Profil joueur Pro",
    "profile.subtitle": "Ton profil de jeu",
    "profile.analysis": "Analyse de {games} parties • Win rate {winRate}%",
    "profile.improving": "↑ En progression",
    "profile.declining": "↓ À améliorer",
    "profile.mainRole": "Rôle principal",
    "profile.winRate": "Win rate",
    "profile.playstyleTitle": "Ton style de jeu",
    "profile.playstyleSubtitle": "Analyse de tes patterns de jeu",
    "profile.insightsTitle": "Insights TheCall",
    "profile.insightsSubtitle": "Analyse personnalisée de ton gameplay",
    "profile.statsTitle": "Stats par rôle",
    "profile.statsSubtitle": "Performance détaillée sur chaque position",
    "profile.trendsTitle": "Tendances",
    "profile.trendsSubtitle": "Évolution sur tes 10 dernières parties",
    "profile.trends.cs": "CS / minute",
    "profile.trends.kp": "Effort collectif",
    "profile.trends.vision": "Contrôle Vision",
    "profile.unavailable": "Profil indisponible",
    "profile.unavailableDesc": "Impossible de charger ton profil.",
    "profile.puuidHint": "Le service est momentanément indisponible.",
    "profile.goToMatches": "Aller sur /match pour charger tes matchs",
    "profile.playstyle.aggression": "Agression",
    "profile.playstyle.objectiveFocus": "Focus objectifs",
    "profile.playstyle.teamFightPresence": "Présence team fights",
    "profile.playstyle.high": "Élevé",
    "profile.playstyle.medium": "Moyen",
    "profile.playstyle.low": "Faible",
    "profile.insight.strength": "Point fort",
    "profile.insight.weakness": "À améliorer",
    "profile.insight.recommendation": "Recommandation",
    "profile.insight.priority": "Priorité",
    "coaching.turningPoint": "Moment clé",
    "coaching.focus": "Focus prioritaire",
    "coaching.action": "Action next game",
    "coaching.rootCauses": "Causes racines",
    "coaching.actionPlan": "Plan d'action",
    "coaching.drills": "Drills / exercices",
    "coaching.phase.early": "Early",
    "coaching.phase.mid": "Mid",
    "coaching.phase.late": "Late",
    "coaching.buildAnalysis.title": "Analyse du Build",
    "coaching.buildAnalysis.subtitle": "Critique & Suggestions",
    "coaching.buildAnalysis.critique": "L'avis du Coach",
    "coaching.buildAnalysis.suggestion": "Suggestion",
    "coaching.buildAnalysis.replace": "À remplacer :",
    "coaching.buildAnalysis.why": "Pourquoi ?",
    "profile.stats.winRate": "Win rate",
    "profile.stats.avgKP": "KP moyen",
    "profile.stats.games": "Games",
    "profile.stats.avgKDA": "KDA moyen",
    "profile.stats.avgGold": "Gold moyen",
    "profile.stats.mostPlayedChampions": "Champions les plus joués",
  },
  en: {
    // Navbar
    "navbar.overview": "Overview",
    "navbar.coach": "Coach",
    "navbar.backToMatches": "Back to matches",
    "navbar.profile": "Profile",
    "navbar.pro": "Pro",
    "navbar.settings": "Settings",
    "navbar.manageSubscription": "Manage subscription",
    "navbar.upgradeToPro": "Upgrade to Pro",
    "navbar.logout": "Log out",
    "navbar.userTierFree": "Free Tier",
    "navbar.userTierPro": "Pro Tier",
    
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account and TheCall preferences.",
    "settings.language": "Language",
    "settings.languageDesc": "Choose the interface language",
    "settings.saving": "Saving...",
    "settings.saved": "Saved!",
    "settings.save": "Save",
    "settings.logout": "Log out",
    "settings.saveError": "Error while saving. Try again.",
    "settings.futureSettings": "More settings will be available soon",
    "settings.tabs.account": "Account",
    "settings.tabs.subscription": "Subscription",
    "settings.tabs.preferences": "Preferences",
    "settings.tabs.security": "Security",
    "settings.tabs.notifications": "Notifications",
    "settings.personalInfo": "Personal Information",
    "settings.personalInfoDesc": "This information is synced via Riot Games and cannot be modified manually.",
    "settings.name": "Name / Username",
    "settings.email": "Email",
    "settings.riotLink": "Riot Games Link",
    "settings.riotConnected": "Riot Account Connected",
    "settings.plan.title": "Your Current Plan",
    "settings.plan.free": "Free Plan",
    "settings.plan.pro": "TheCall Pro",
    "settings.plan.active": "Active Member",
    "settings.plan.upgrade": "Upgrade to Pro",
    "settings.plan.freeDesc": "Limit of {count} analyses per month. Upgrade to Pro to never miss out.",
    "settings.plan.proDesc": "You benefit from all unlimited premium analyses.",
    "settings.billing.title": "Billing Details",
    "settings.billing.status": "Status",
    "settings.billing.renewal": "Renewal",
    "settings.billing.founder": "Founder Member",
    "settings.billing.founderThanks": "Thanks for supporting TheCall at launch! 💜",
    "settings.billing.manage": "Manage my subscription via Stripe",
    "settings.billing.adminManaged": "Managed by an Administrator",
    "settings.billing.cancelNotice": "Will be canceled on this date",
    "settings.usage.title": "Usage",
    "settings.usage.analyses": "Analyses this month",
    "settings.look.title": "Interface & Look",
    "settings.look.dynamicTheme": "Dynamic Theme",
    "settings.look.dynamicThemeDesc": "The interface adapts its colors (Win, Loss or Neutral) based on your match results.",
    "settings.look.animations": "Advanced Animations",
    "settings.look.animationsDesc": "Enable smooth transitions, particle effects and micro-interactions.",
    "settings.privacy.title": "Privacy",
    "settings.privacy.public": "Public Profile",
    "settings.privacy.publicDesc": "Allow other players to see your statistics and reports.",
    "settings.security.password": "Password",
    "settings.security.unavailable": "Password change (Unavailable at the moment)",
    "settings.notifications.channels": "Channels",
    "settings.notifications.push": "Push Notifications",
    "settings.notifications.pushDesc": "Alert when a new report is ready.",
    "settings.notifications.newsletter": "Newsletter & Tips",
    "settings.notifications.newsletterDesc": "Receive the best weekly tips by email.",
    
    // Subscription
    "subscription.title": "Subscription management",
    "subscription.subtitle": "Manage your Pro subscription",
    "subscription.planPro": "Pro Plan",
    "subscription.planFree": "Free Plan",
    "subscription.proDesc": "Full access to all features",
    "subscription.freeDesc": "Limited access to basic features",
    "subscription.active": "ACTIVE",
    "subscription.renewalDate": "Auto-renewal on",
    "subscription.cancelling": "Your subscription will be cancelled at the end of the billing period",
    "subscription.actions": "Actions",
    "subscription.cancel": "Cancel subscription",
    "subscription.reactivate": "Reactivate subscription",
    "subscription.downgrade": "Downgrade to free immediately",
    "subscription.upgradeTitle": "Upgrade to Pro",
    "subscription.upgradeDesc": "Unlock all premium features",
    "subscription.viewOffers": "View offers",
    "subscription.paymentInfo": "Payment information",
    "subscription.paymentInfoDesc": "Payment method management will be available soon",
    "subscription.cancelConfirmTitle": "Cancel subscription?",
    "subscription.cancelConfirmDesc": "Your subscription will remain active until the end of the billing period ({date}). You can always reactivate before this date.",
    "subscription.downgradeConfirmTitle": "Downgrade to free?",
    "subscription.downgradeConfirmDesc": "You will immediately lose access to Pro features. This action is irreversible until you upgrade to Pro again.",
    "subscription.processing": "Processing...",
    "subscription.confirm": "Confirm",
    "subscription.cancelAction": "Cancel",
    "subscription.loading": "Loading...",
    
    // Landing Page
    "landing.beta": "Private Beta",
    "landing.focus": "Macro focus",
    "landing.postGame": "Post-game coaching",
    "landing.tagline": "The Call • League of Legends Coaching",
    "landing.title": "You're stuck and don't understand why?",
    "landing.titleHighlight": "TheCall",
    "landing.titleEnd": "shows you where the game turns.",
    "landing.subtitle": "TheCall — your post-game macro coach.",
    "landing.description": "No more stats without explanation. You understand the key moment when it turns, the root cause (macro, tempo, objectives), and a concrete plan for your next game.",
    "landing.analyzeButton": "Analyze my last game",
    "landing.riotConnect": "Riot Connection (coming soon)",
    "landing.riotConnectTitle": "Riot connection via RSO — pending validation",
    "landing.fastReport": "Report in less than 5s",
    "landing.roleAdapted": "Adapted to your role (Top, Jungle, Mid, Bot, Support)",
    "landing.taglineShort": "Understand the turn • Fix the cause • Progress.",
    "landing.targetAudience": "For Bronze → Gold players who want to climb a tier. No generic advice: actionable insights.",
    "landing.riotIdLabel": "Enter my Riot ID",
    "landing.riotIdPlaceholder": "BNJ#EUW",
    "landing.riotIdFormat": "Format: gameName#tag (ex: BNJ#EUW)",
    "landing.analyzeButtonForm": "Analyze",
    "landing.feature1Title": "The key moment",
    "landing.feature1Desc": "You see the exact moment when the game turns — and the cause (priority, vision, reset, forced fight). No more vague \"I played badly\": you know exactly what to fix.",
    "landing.feature1Proof": "Key moment: 15:23",
    "landing.feature2Title": "The root cause",
    "landing.feature2Desc": "We tell you why it turned (macro, tempo, objectives). If you win your lane but lose the game, you understand the pattern — and how to fix it.",
    "landing.feature2Proof": "Cause: tempo lost at 12 min",
    "landing.feature3Title": "Your next game plan",
    "landing.feature3Desc": "A simple, actionable instruction for your next game. Not another analysis: an instruction to apply immediately.",
    "landing.feature3Proof": "Plan: reset + vision 40s before",
    "landing.exampleTitle": "Example report",
    "landing.exampleKeyMoment": "Key moment",
    "landing.exampleKeyMomentText": "15:23 — Herald fight lost due to lack of river vision.",
    "landing.exampleKeyMomentConsequence": "Consequence: tempo lost, mid priority reversed. Focus vision + reset before objectives.",
    "landing.exampleRootCause": "Root cause",
    "landing.exampleRootCauseText": "Gold ahead +1,240 at 20 min, but late global impact.",
    "landing.exampleRootCauseDetail": "You win your lane, but your moves come too late. We tell you why and how to fix it (roams from 12 min).",
    "landing.exampleAction": "Next action",
    "landing.exampleActionText": "14:40 — Reset + bot river vision.",
    "landing.exampleActionDetail": "Arrive 10s early to setup before Drake spawn. You regain tempo.",
    "landing.howItWorks1": "We retrieve your last game (via Riot API).",
    "landing.howItWorks2": "We isolate the key moment + your priority focus.",
    "landing.howItWorks3": "You leave with a simple action to apply next game.",
    "landing.coachingTitle": "What coaching looks like",
    "landing.coachingSubtitle": "In 60 seconds: 1 key moment, 1 focus, 1 next game action.",
    "landing.coachingExample": "Example feedback you can receive",
    "landing.coachingExample1": "Gold ahead but tempo lost: we point out when you lose control and why.",
    "landing.coachingExample2": "Lane lead but weak global impact: we tell you how to fix it (rotations + objectives from 12 min).",
    "landing.previewWinProb": "Win probability • Example",
    "landing.previewWinProbValue": "72% win • Mid game",
    "landing.previewKeyMoment": "Key moment:",
    "landing.previewHerald": "Herald fight lost",
    "landing.previewMacro": "Macro",
    "landing.previewMacroScore": "Good tempo",
    "landing.previewMacroValue": "Score: 78/100",
    "landing.previewLaning": "Laning",
    "landing.previewLaningScore": "Advantage",
    "landing.previewLaningValue": "Score: 84/100",
    "landing.previewDecisions": "Decisions",
    "landing.previewDecisionsScore": "To fix",
    "landing.previewDecisionsValue": "Score: 62/100",
    
    // Matches
    "matches.title": "My matches",
    "matches.subtitle": "Select a match to see details",
    "matches.noMatches": "No matches available",
    "matches.error": "Service disrupted",
    "matches.errorDesc": "Communication with Riot services is difficult.",
    "matches.errorSolution": "Suggestions:",
    "matches.errorStep1": "Check your internet connection",
    "matches.errorStep2": "Riot servers might be overloaded",
    "matches.errorStep3": "Try again in a few moments",
    "matches.loading": "Loading matches...",
    "matches.selectMatch": "Select a match",
    
    // Common
    "common.back": "Back",
    "common.loading": "Loading...",
    "common.guest": "Guest",
    "settings.french": "French",
    "settings.english": "English",
    "subscription.upgradeConfirmTitle": "Upgrade to Pro? (Dev Mode)",
    "subscription.upgradeConfirmDesc": "In development mode, you can test upgrading to Pro. The page will reload to apply changes.",
    
    // Loading
    "loading.messages.poro": "Petting the Poros...",
    "loading.messages.stats": "Calculating statistics...",
    "loading.messages.gameplay": "Analyzing gameplay...",
    "loading.messages.nexus": "Inspecting the Nexus...",
    "loading.messages.runes": "Loading rune shards...",

    // Tips
    "tips.herald": "Tip: Hit the eye on the Herald's back to deal massive true damage.",
    "tips.wards": "Tip: Save your free ward to detect an early invade in the first minute.",
    "tips.recall": "Tip: Don't sit on 1500 gold. Recall to turn your advantage into items.",
    "tips.objective": "Tip: A kill without an objective (tower, drake) is just a stat, not a win.",
    "tips.spacing": "Tip: Spacing is key. Keep max distance to punish without being punished.",
    "tips.level2": "Tip: The 7th minion (solo lane) gives level 2. Be ready to engage first!",
    "tips.vision": "Tip: Vision Score isn't just for supports. Place deep wards in the enemy jungle.",
    "tips.tempo": "Tip: Tempo is a resource. If you wait too long, the opportunity vanishes.",

    // Match
    "match.notFound": "Match not found",
    "match.notFoundDesc": "This match does not exist in your list.",
    "match.unavailable": "Match unavailable",
    "match.unavailableDesc": "Unable to load match details.",
    "match.noOpponent": "Unable to identify opponent (role match).",
    "match.matchCenter": "The Call • Match Center",
    "match.matchOverview": "Match Overview",
    "match.matchOverviewDesc": "Timeline, duel, builds and AI audit — LoL client style.",
    "match.result": "Result",
    "match.yourRole": "Your role",
    "match.yourChampion": "Your champion",
    "match.timelineTitle": "Timeline",
    "match.timelineSubtitle": "Key events of the game",
    "match.duelTitle": "Duel",
    "match.duelSubtitle": "You vs your opponent",
    "match.buildsTitle": "Builds",
    "match.buildsSubtitle": "Items & runes used in the match",
    "match.teamsTitle": "Teams",
    "match.teamsSubtitle": "Team composition",
    "match.yourTeam": "Your team",
    "match.enemyTeam": "Enemy team",
    "match.you": "You",
    "match.opponent": "Opponent",
    
    // Builds
    "build.yourBuild": "Your build",
    "build.opponentBuild": "Opponent's build",
    "build.title": "Build in the game",
    "build.subtitle": "Items & runes used in the game",
    "build.items": "Items",
    "build.runes": "Runes",
    
    // Auth
    "auth.title": "Connect via Riot",
    "auth.subtitle": "Riot Auth (placeholder)",
    "auth.description": "This page is ready to connect Riot OAuth (client_id, redirect_uri, scopes). We will redirect the user to the authorization URL, then process the return code to exchange a token and retrieve the PUUID.",
    "auth.vars": "Prepare vars: RIOT_CLIENT_ID, RIOT_CLIENT_SECRET, RIOT_REDIRECT_URI.",
    "auth.waiting": "While waiting for OAuth, you can switch to \"already connected\" mode via the link below.",
    "auth.continue": "Continue (mock connected)",
    "auth.back": "Back to home",
    
    // Match List
    "matchList.loading": "Loading...",
    "matchList.vs": "VS",
    "matchList.vsShort": "vs",
    "matchList.victory": "VICTORY",
    "matchList.defeat": "DEFEAT",
    "matchList.victoryShort": "W",
    "matchList.defeatShort": "L",
    "matchList.queueRankedSolo": "Ranked Solo",
    "matchList.queueRankedFlex": "Ranked Flex",
    "matchList.queueAram": "ARAM",
    "matchList.queueNormalDraft": "Normal Draft",
    "matchList.queueClash": "Clash",
    "matchList.queueNormal": "Normal",
    "matchList.totalGames": "Games",
    "matchList.winrate": "WinRate",
    
    // Match Type Filter
    "matchType.all": "All matches",
    "matchType.draft": "Draft",
    "matchType.ranked": "Ranked",
    
    // Cookies
    "cookies.title": "We use cookies",
    "cookies.description": "We use cookies to improve your experience, manage sessions and analyze site usage. By continuing, you accept our use of cookies.",
    "cookies.acceptAll": "Accept all",
    "cookies.rejectAll": "Reject all",
    "cookies.customize": "Customize",
    "cookies.settingsTitle": "Cookie settings",
    "cookies.savePreferences": "Save preferences",
    "cookies.learnMore": "Learn more",
    "cookies.necessaryTitle": "Necessary cookies",
    "cookies.necessaryDesc": "These cookies are essential for the site to function. They cannot be disabled.",
    "cookies.functionalTitle": "Functional cookies",
    "cookies.functionalDesc": "These cookies improve functionality like rate limiting and session management for a better experience.",
    "cookies.analyticsTitle": "Analytics cookies",
    "cookies.analyticsDesc": "These cookies help us understand how you use the site to improve it.",
    "cookies.alwaysActive": "Always active",
    
    // Privacy
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "Data protection and cookie usage",
    "privacy.intro": "At TheCall, we respect your privacy and are committed to protecting your personal data. This policy explains how we collect, use and protect your information.",
    "privacy.cookiesTitle": "Cookie Usage",
    "privacy.necessaryCookies": "Necessary cookies",
    "privacy.necessaryCookiesDesc": "These cookies are essential for the site to function. They maintain your session, secure requests and ensure basic functionality. They cannot be disabled.",
    "privacy.functionalCookies": "Functional cookies",
    "privacy.functionalCookiesDesc": "These cookies improve your experience by enabling personalized rate limiting, session management and other features that require recognizing you between visits. You can accept or reject them.",
    "privacy.analyticsCookies": "Analytics cookies",
    "privacy.analyticsCookiesDesc": "These cookies help us understand how you use the site (pages visited, time spent, etc.) to improve our services. You can accept or reject them.",
    "privacy.dataTitle": "Data Collected",
    "privacy.dataDesc": "We only collect data necessary for the service to function:",
    "privacy.dataList1": "Riot ID and match data (via Riot Games API)",
    "privacy.dataList2": "Language preferences and interface settings",
    "privacy.dataList3": "Session data for rate limiting and security",
    "privacy.rightsTitle": "Your Rights (GDPR)",
    "privacy.rightsDesc": "In accordance with GDPR, you have the right to:",
    "privacy.rightsList1": "Access your personal data",
    "privacy.rightsList2": "Rectify or delete your data",
    "privacy.rightsList3": "Object to the processing of your data",
    "privacy.rightsList4": "Withdraw your consent at any time",
    "privacy.contactTitle": "Contact",
    "privacy.contactDesc": "For any questions about this policy or to exercise your rights, contact us through available support channels.",
    "footer.legal": "Legal Notice",
    "footer.privacy": "Privacy Policy",
    "footer.crafted": "Crafted with ❤️ by TheCall Team.",
    
    // Coaching
    "coaching.title": "Coaching TheCall",
    "coaching.subtitle": "Post-match analysis with personalized insights",
    "coaching.progressionObjectives": "Progression objectives",
    "coaching.moreObjectives": "+{count} more objectives available with Pro",
    "coaching.strengths": "Strengths",
    "coaching.weaknesses": "Areas to improve",
    "coaching.moreStrengths": "+{count} more strengths with Pro",
    "coaching.moreWeaknesses": "+{count} more areas to improve with Pro",
    "coaching.errorsToAvoid": "Errors to avoid:",
    "coaching.games": "games",
    "coaching.quotaExhausted": "Coaching quota exhausted",
    "coaching.quotaExhaustedDesc": "Upgrade to Pro for unlimited coaching + full profile",
    "coaching.impact": "Impact:",
    "coaching.aiLoading": "AI is analyzing your game...",
    
    // Profile
    "profile.title": "The Call • Pro Player Profile",
    "profile.subtitle": "Your gameplay profile",
    "profile.analysis": "Analysis of {games} games • Win rate {winRate}%",
    "profile.improving": "↑ Improving",
    "profile.declining": "↓ Needs improvement",
    "profile.mainRole": "Main role",
    "profile.winRate": "Win rate",
    "profile.playstyleTitle": "Your playstyle",
    "profile.playstyleSubtitle": "Analysis of your gameplay patterns",
    "profile.insightsTitle": "TheCall Insights",
    "profile.insightsSubtitle": "Personalized analysis of your gameplay",
    "profile.statsTitle": "Stats by role",
    "profile.statsSubtitle": "Detailed performance on each position",
    "profile.trendsTitle": "Trends",
    "profile.trendsSubtitle": "Performance evolution over your last 10 games",
    "profile.trends.cs": "CS / minute",
    "profile.trends.kp": "Collective Effort",
    "profile.trends.vision": "Vision Control",
    "profile.unavailable": "Profile unavailable",
    "profile.unavailableDesc": "Unable to load your profile.",
    "profile.puuidHint": "Service is temporarily unavailable.",
    "profile.goToMatches": "Go to /match to load your matches",
    "profile.playstyle.aggression": "Aggression",
    "profile.playstyle.objectiveFocus": "Objective focus",
    "profile.playstyle.teamFightPresence": "Team fight presence",
    "profile.playstyle.high": "High",
    "profile.playstyle.medium": "Medium",
    "profile.playstyle.low": "Low",
    "profile.insight.strength": "Strength",
    "profile.insight.weakness": "To improve",
    "profile.insight.recommendation": "Recommendation",
    "profile.insight.priority": "Priority",
    "coaching.turningPoint": "Key moment",
    "coaching.focus": "Priority focus",
    "coaching.action": "Next game action",
    "coaching.rootCauses": "Root causes",
    "coaching.actionPlan": "Action plan",
    "coaching.drills": "Drills / exercises",
    "coaching.phase.early": "Early",
    "coaching.phase.mid": "Mid",
    "coaching.phase.late": "Late",
    "coaching.buildAnalysis.title": "Build Analysis",
    "coaching.buildAnalysis.subtitle": "Critique & Suggestions",
    "coaching.buildAnalysis.critique": "Coach's Verdict",
    "coaching.buildAnalysis.suggestion": "Suggestion",
    "coaching.buildAnalysis.replace": "Replace:",
    "coaching.buildAnalysis.why": "Why?",
    "profile.stats.winRate": "Win rate",
    "profile.stats.avgKP": "Average KP",
    "profile.stats.games": "Games",
    "profile.stats.avgKDA": "Average KDA",
    "profile.stats.avgGold": "Average Gold",
    "profile.stats.mostPlayedChampions": "Most played champions",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    // Determine language after mount to avoid hydration mismatch
    const savedLanguage = typeof window !== "undefined" ? localStorage.getItem("language") : null;
    const browserLang = typeof window !== "undefined" ? navigator.language.slice(0, 2) : "en";
    
    const initialLang = (savedLanguage === "en" || savedLanguage === "fr") 
      ? savedLanguage 
      : (browserLang === "fr" ? "fr" : "en");
    
    setLanguageState(initialLang as Language);
    setMounted(true);
  }, []);

  const setLanguage = useCallback((lang: string) => {
    const normalized = (lang === "us" || lang === "en") ? "en" : "fr";
    setLanguageState(normalized as Language);
    if (typeof window !== "undefined") {
      localStorage.setItem("language", normalized);
    }
  }, []);

  const t = useCallback((key: string, params?: Record<string, string>): string => {
    // If not mounted, ALWAYS use "en" (or whatever the server used)
    const effectiveLang = mounted ? language : "en";
    const activeLang = (effectiveLang === "en" || effectiveLang === "fr") ? effectiveLang : "en";
    
    const translation = translations[activeLang]?.[key] || translations["en"]?.[key] || key;
    if (params) {
      return Object.entries(params).reduce(
        (str, [param, value]) => str.replace(new RegExp(`\\{${param}\\}`, "g"), value),
        translation
      );
    }
    return translation;
  }, [language, mounted]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t
  }), [language, setLanguage, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
